Feature: Process IPNs
  As a developer
  I want to make sure that the IPNs communicated back-and-forth between PayPal and our PayPal application client (app)
  are managed by the PayPal IPN Processor (PIP) to be reliably transmitted and not lost or corrupted
  So that resulting bugs caused by IPN transmission error are eliminated or stopped

  # "Sunny day" scenarios:
  Scenario: PayPal sends IPN
    Given that PayPal, the PIP, and the app have been linked together
    When PayPal sends an IPN to the PIP
    Then the PIP immediately acknowledges success on the send
    And it queues the received IPN to be sent back to PayPal

  Scenario: PIP sends IPN back to PayPal for a successful verification
    Given that PIP has at least one IPN in its queue to be acknowledged
    When the PIP sends the IPN back to PayPal for acknowledgement
    Then PayPal replies that the IPN is verified
    And the PIP queues the IPN to be transmitted to the app

  Scenario: App receives IPN from PIP
    Given that the PIP has at least one IPN that has been verified in its queue to be sent to the app
    When the PIP completes acknowledgement verification for that IPN
    Then the PIP sends the IPN to the app as a new record in its database

  # Performance optimizations to prevent bottle-necking sometimes and to prevent overloading in others
  Scenario: PIP sends acknowledgement requests to PayPal in series in the order that PayPal sent them to the PIP
    Given that PayPal has 50 IPNs to send to the PIP
    When the PIP receives an IPN
    Then it delegates the PIP to a separate server process for handling
    And it can quickly respond to the next IPN request from PayPal.
    And the server process sends its next acknowledgement request to PayPal.

  Scenario: IPNs for a given subscription are sent to the app's database in sequential order
    Given that PayPal has a create payment and a recurring payment for the same subscription in a batch of 50 IPNs
    When the PIP receives the create payment IPN
    Then it delegates it to the server process for PayPal to verify it.
    When it receives the recurring payment IPN
    Then it delegates it to the same server process which handles its requests sequentially
    When the PIP receives the create payemnt verification from PayPal
    Then it delegates it to the server process that sends the IPN to the app's database.
    When it receives the recurring payment IPM verification from PayPal
    Then it delegates it to the same server process that sends the IPN to the app's database.
    And the app will receive the create payment IPN
    And then the app will receive the recurring payment IPN

  # Verification boundary condition checks:
  Scenario: PIP throws away IPN generated by hacker that PayPal said was invalid
    Given that the PIP has at least one IPN in its queue to be acknowledged
    And it was received from a hacker who sent it attempting to hack the sysytem
    When the PIP sends the IPN back to PayPal for acknowledgement
    Then PayPal replies that the IPN is invalid
    And the PIP logs the rogue IPN
    And it notifies the development team indicating that it received a rogue IPN

  Scenario: PIP acknowledgement request to PayPal times out once
    Given that the PIP has at least one IPN in its queue to be acknowledged
    When the PIP sends the IPN back to PayPal for acknowledgement
    And PayPal never responds at all
    Then the PIP times out on that request
    And it logs the request as a warning
    When it reissues the request
    Then PayPal replies that the IPN is verified
    And the PIP forwards the IPN to the app's database

  Scenario: PayPal times out every time on a IPN acknowledgement request
    Given that the PIP has at least one IPN in its queue to be acknowledged
    When PayPal fails to respond after 3 acknowledgement requests
    Then the PIP logs an error that PayPal is unavailable
    And it notifies the development team that PayPal is unable to process acknowledgements for this IPN
    And it continues to receive and cache IPN requests from PayPal
    And it waits an increasing amount of time each time before retrying sending ack request to PayPal for the current IPN.

  Scenario: IPN received for subscription having a previous IPN that failed to be acknowledged
    Given that the PIP was unable to process an IPN
    When the PIP receives a new IPN in the same subscription as the previous IPN
    Then it notifies the development team that an IPN cannot be processed because a previous IPN in the subscription failed ack
    And it processes a PayPal acknowledgment
    But it does not transmit the IPN to the app's database

  Scenario: App replies internal error when the PIP attempts to send an IPN to it
    Given that the PIP has at least one IPN that has been verified in its queue to be sent to the app
    When the PIP sends the IPN to the app's database
    And later on the app encounters an internal error when it processes the IPN
    Then the app logs the IPN that the it won't process
    And it notifies the development team that the app is unable to process this IPN

  Scenario: App's database times out when the PIP attempts to send an IPN to it
    Given that the PIP has at least one IPN that has been verified in its queue to be sent to the app's database.
    When the PIP sends the IPN to the app's database
    And the app never responds at all
    Then the PIP times out the request
    And it logs the IPN that the app won't process as a warning
    When it again tries to send the IPN to the app's database
    Then this time it succeeds
    And it processes the next IPN in its queue.

  Scenario: App's database is unavailable to the PIP
    Given that the PIP has at least one IPN that has been verified in its queue to be sent to the app's database.
    When the PIP sends the IPN to the app's database
    And the app' database fails to respond after 3 write requests
    Then the PIP notifies the development team that the app has timed out 3 times in a row
    And it waits an increasing amount of time each time before retrying sending the IPN to the app's database.
